language: php
os:
  - linux
php:
  - 7.4
  - 7.3
  - 7.2
  - 5.6

env:
  - TEST_SUITE=Unit
    COMPOSER_VERSION=1.9.2
  - TEST_SUITE=Fullstack
    COMPOSER_VERSION=1.9.2

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TEST_SUITE=Static
    - php: 7.0
      env: TEST_SUITE=Static
    - php: 7.4
      os: windows
    - php: 7.4
      env: COMPOSER_VERSION=dev
  allow_failures:
    - os: windows
    - env: TEST_SUITE=Static
    - env: COMPOSER_VERSION=beta
    - env: COMPOSER_VERSION=dev

cache:
  directories:
  - $HOME/.composer/cache

install:
  - php ./tests/prepare_composer.php
  - chmod +x ./composer.phar
  - ./composer.phar --version
  - ./composer.phar install -n --prefer-source

script:
  - >
    sh -c "if [ '$TEST_SUITE' = 'Unit' ] || [ '$TEST_SUITE' = 'Fullstack' ]; then
    ./vendor/bin/phpunit --coverage-clover=coverage.clover --testsuite=$TEST_SUITE;
    fi"
  - >
    sh -c "if [ '$TEST_SUITE' = 'Static' ]; then
    ./vendor/bin/phpcs --standard=PSR2 ./src/;
    ./vendor/bin/phpcs --standard=PSR2 ./tests/MagentoHackathon;
    fi"
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
